items:
- uid: System.IO.InvalidDataException
  commentId: T:System.IO.InvalidDataException
  id: InvalidDataException
  parent: System.IO
  children:
  - System.IO.InvalidDataException.#ctor
  - System.IO.InvalidDataException.#ctor(System.String)
  - System.IO.InvalidDataException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: InvalidDataException
  fullName: System.IO.InvalidDataException
  type: Class
  source:
    remote:
      path: src/System.IO/src/System/IO/InvalidDataException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: InvalidDataException
    path: src/System.IO/src/System/IO/InvalidDataException.cs
    startLine: 6
  assemblies:
  - System.IO
  namespace: System.IO
  summary: "\n<p>The exception that is thrown when a data stream is in an invalid format.</p>\n"
  remarks: "\n<p>An <xref href=\"System.IO.InvalidDataException\" data-throw-if-not-resolved=\"false\"></xref> is thrown when invalid data is detected in the data stream.</p>\n"
  example:
  - 
  syntax:
    content: 'public sealed class InvalidDataException : Exception'
    content.vb: >-
      Public NotInheritable Class InvalidDataException
          Inherits Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: System.IO.InvalidDataException.#ctor
  commentId: M:System.IO.InvalidDataException.#ctor
  id: '#ctor'
  parent: System.IO.InvalidDataException
  langs:
  - csharp
  - vb
  name: InvalidDataException()
  fullName: System.IO.InvalidDataException.InvalidDataException()
  type: Constructor
  source:
    remote:
      path: src/System.IO/src/System/IO/InvalidDataException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.IO/src/System/IO/InvalidDataException.cs
    startLine: 8
  assemblies:
  - System.IO
  namespace: System.IO
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.IO.InvalidDataException\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: "\n<p>This constructor initializes the <xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref> property of the new instance to a system-supplied message that describes the error, such as \"An invalid argument was specified.\" This message is localized based on the current system culture.</p>\n"
  example:
  - 
  syntax:
    content: public InvalidDataException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.IO.InvalidDataException.#ctor(System.String)
  commentId: M:System.IO.InvalidDataException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IO.InvalidDataException
  langs:
  - csharp
  - vb
  name: InvalidDataException(String)
  fullName: System.IO.InvalidDataException.InvalidDataException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.IO/src/System/IO/InvalidDataException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.IO/src/System/IO/InvalidDataException.cs
    startLine: 13
  assemblies:
  - System.IO
  namespace: System.IO
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.IO.InvalidDataException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message.</p>\n"
  remarks: "\n<p>This constructor initializes the <xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref> property of the new instance to a system-supplied message that describes the error, such as \"An invalid argument was specified.\" This message is localized based on the current system culture.</p>\n"
  example:
  - 
  syntax:
    content: public InvalidDataException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that explains the reason for the exception.</p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.IO.InvalidDataException.#ctor(System.String,System.Exception)
  commentId: M:System.IO.InvalidDataException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IO.InvalidDataException
  langs:
  - csharp
  - vb
  name: InvalidDataException(String, Exception)
  fullName: System.IO.InvalidDataException.InvalidDataException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.IO/ref/System.IO.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.IO/ref/System.IO.cs
    startLine: 113
  assemblies:
  - System.IO
  namespace: System.IO
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.IO.InvalidDataException\" data-throw-if-not-resolved=\"false\"></xref> class with a reference to the inner exception that is the cause of this exception.</p>\n"
  remarks: "\n<p>This constructor initializes the <xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref> property of the new instance using the value of the <em>message</em> parameter. The content of the <em>message</em> parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</p>\n<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property returns the same value that is passed into the constructor, or <strong>null</strong> if the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property does not supply the inner exception value to the constructor.</p>\n"
  example:
  - 
  syntax:
    content: public InvalidDataException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that explains the reason for the exception.</p>\n"
    - id: innerException
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception. If the <em>innerException</em> parameter is not <strong>null</strong>, the current exception is raised in a <strong>catch</strong> block that handles the inner exception.</p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.IO
  isExternal: false
  name: System.IO
  fullName: System.IO
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
