items:
- uid: System.Security.Authentication.AuthenticationException
  id: AuthenticationException
  parent: System.Security.Authentication
  children:
  - System.Security.Authentication.AuthenticationException.#ctor
  - System.Security.Authentication.AuthenticationException.#ctor(System.String)
  - System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)
  href: System.Security.Authentication.AuthenticationException.yml
  name: AuthenticationException
  fullName: System.Security.Authentication.AuthenticationException
  type: Class
  source:
    remote: &o0
      path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
    startLine: 10
  assemblies:
  - System.Net.Security
  namespace: System.Security.Authentication
  summary: The exception that is thrown when authentication fails for an authentication stream.
  syntax:
    content: 'public class AuthenticationException : Exception'
    content.vb: Public Class AuthenticationException Inherits Exception
  inheritance:
  - System.Object
- uid: System.Security.Authentication.AuthenticationException.#ctor
  id: '#ctor'
  parent: System.Security.Authentication.AuthenticationException
  href: System.Security.Authentication.AuthenticationException.yml
  name: AuthenticationException()
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException()
  type: Constructor
  source:
    remote: *o0
    path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
    startLine: 12
  assemblies:
  - System.Net.Security
  namespace: System.Security.Authentication
  summary: Initializes a new instance of the @'System.Security.Authentication.AuthenticationException' class with no message.
  syntax:
    content: public AuthenticationException()
    content.vb: Public Sub New
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Security.Authentication.AuthenticationException
  href: System.Security.Authentication.AuthenticationException.yml
  name: AuthenticationException(String)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(System.String)
  type: Constructor
  source:
    remote: *o0
    path: src/System.Net.Security/src/System/Net/SecureProtocols/AuthenticationException.cs
    startLine: 13
  assemblies:
  - System.Net.Security
  namespace: System.Security.Authentication
  summary: Initializes a new instance of the @'System.Security.Authentication.AuthenticationException' class with the specified message.
  syntax:
    content: public AuthenticationException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: A @'System.String' that describes the authentication failure.
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Security.Authentication.AuthenticationException
  href: System.Security.Authentication.AuthenticationException.yml
  name: AuthenticationException(String, Exception)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Net.Security/ref/System.Net.Security.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Net.Security/ref/System.Net.Security.cs
    startLine: 118
  assemblies:
  - System.Net.Security
  namespace: System.Security.Authentication
  summary: Initializes a new instance of the @'System.Security.Authentication.AuthenticationException' class with the specified message and inner exception.
  syntax:
    content: public AuthenticationException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: A @'System.String' that describes the authentication failure.
    - id: innerException
      type: System.Exception
      description: The @'System.Exception' that is the cause of the current exception.
references:
- uid: System.Security.Authentication
  isExternal: false
  name: System.Security.Authentication
  fullName: System.Security.Authentication
- uid: System.Object
  parent: System
  isExternal: false
  href: System.Object.yml
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  href: System.String.yml
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  href: System.Exception.yml
  name: Exception
  fullName: System.Exception
